// 
// POINTLESS TO MODIFY THIS FILE - IT'S AUTO-GENERATED BY COOK_FONT.PY from TEMPLATE_KERNED_FONT.H
// 

#ifndef BUREAU_FONT_INCLUDED
#define BUREAU_FONT_INCLUDED

#include "video/font.h"

namespace game {

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class BureauFont : public engine::KernedFont {
	static const uint GLYPH_FIRST = 32;
	static const uint GLYPH_COUNT = 224;

	static const uint KERN_FIRST = 65;
	static const uint KERN_COUNT = 57;

	static const uint KERN_MAP_FIRST = 44;
	static const uint KERN_MAP_COUNT = 78;

	static const Font::Glyph GLYPH_DATA[];
	static const Font::Glyph* const GLYPHS[GLYPH_COUNT];

	static const i8 KERN_DATA[][KERN_MAP_COUNT];
	static const i8* const KERNINGS[KERN_COUNT];

	static const Font::Info INFO;

public:
	BureauFont() : KernedFont(INFO, GLYPHS, GLYPH_FIRST, GLYPH_FIRST + GLYPH_COUNT, 
		KERNINGS, KERN_FIRST, KERN_FIRST + KERN_COUNT, KERN_MAP_FIRST, KERN_MAP_FIRST + KERN_MAP_COUNT)
	{}
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}

#endif