// 
// POINTLESS TO MODIFY THIS FILE - IT'S AUTO-GENERATED BY COOK_FONT.PY from TEMPLATE_KERNED_FONT.H
// 

#ifndef ${font_name_up}_FONT_INCLUDED
#define ${font_name_up}_FONT_INCLUDED

namespace game {

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class ${font_name}Font : public engine::KernedFont {
	static const uint GLYPH_FIRST = ${glyph_first};
	static const uint GLYPH_COUNT = ${glyph_count};

	static const uint KERN_FIRST = ${kern_first};
	static const uint KERN_COUNT = ${kern_count};

	static const uint KERN_MAP_FIRST = ${kern_map_first};
	static const uint KERN_MAP_COUNT = ${kern_map_count};

	static const Font::Glyph GLYPH_DATA[];
	static const Font::Glyph* const GLYPHS[GLYPH_COUNT];

	static const i8 KERN_DATA[][KERN_MAP_COUNT];
	static const i8* const KERNINGS[KERN_COUNT];

	static const Font::Info INFO;

public:
	${font_name}Font() : KernedFont(INFO, GLYPHS, GLYPH_FIRST, GLYPH_FIRST + GLYPH_COUNT, 
		KERNINGS, KERN_FIRST, KERN_FIRST + KERN_COUNT, KERN_MAP_FIRST, KERN_MAP_FIRST + KERN_MAP_COUNT)
	{}
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}

#endif