// 
// POINTLESS TO MODIFY THIS FILE - IT'S AUTO-GENERATED BY COOK_FONT.PY from TEMPLATE_FONT_DATA.H
// 

const engine::Font::Glyph game::${font_name}Font::GLYPH_DATA[] = {
${glyph_data}};

const engine::Font::Glyph* const game::${font_name}Font::GLYPHS[GLYPH_COUNT] = {
${glyph_index}};

const i8 engine::${font_name}Font::KERN_DATA[][KERN_MAP_COUNT] = {
${kern_data}};

const i8* const engine::${font_name}Font::KERNINGS[KERN_COUNT] = {
${kern_index}};

const engine::Font::Info game::${font_name}Font::INFO = {
	${info}
};

