// 
// POINTLESS TO MODIFY THIS FILE - IT'S AUTO-GENERATED BY COOK_FONT.PY from TEMPLATE_FONT.H
// 

#ifndef ${font_name_up}_FONT_INCLUDED
#define ${font_name_up}_FONT_INCLUDED

namespace game {

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class ${font_name}Font : public engine::Font {
	static const uint GLYPH_FIRST = ${glyph_first};
	static const uint GLYPH_COUNT = ${glyph_count};

	static const Font::Glyph GLYPH_DATA[];
	static const Font::Glyph* const GLYPHS[GLYPH_COUNT];

	static const Font::Info INFO;

public:
	${font_name}Font() : Font(INFO, GLYPHS, GLYPH_FIRST, GLYPH_FIRST + GLYPH_COUNT)
	{}
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}

#endif
