// 
// POINTLESS TO MODIFY THIS FILE - IT'S AUTO-GENERATED BY COOK_FONT.PY from TEMPLATE_FONT_DATA.H
// 

const engine::Font::Glyph engine::${font_name}Font::GLYPH_DATA[] = {
${glyph_data}};

const engine::Font::Glyph* const engine::${font_name}Font::GLYPHS[GLYPH_COUNT] = {
${glyph_index}};

const engine::Font::Info engine::${font_name}Font::INFO = {
${info}
};
