// 
// POINTLESS TO MODIFY THIS FILE - IT'S AUTO-GENERATED BY COOK_FONT.PY from TEMPLATE_KERNED_FONT.H
// 

#ifndef CANDARA_FONT_INCLUDED
#define CANDARA_FONT_INCLUDED

namespace engine {

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class CandaraFont : public KernedFont {
	static const uint GLYPH_FIRST = 0;
	static const uint GLYPH_COUNT = 1170;

	static const uint KERN_FIRST = 33;
	static const uint KERN_COUNT = 190;

	static const uint KERN_MAP_FIRST = 35;
	static const uint KERN_MAP_COUNT = 221;

	static const Font::Glyph GLYPH_DATA[];
	static const Font::Glyph* const GLYPHS[GLYPH_COUNT];

	static const i8 KERN_DATA[][KERN_MAP_COUNT];
	static const i8* const KERNINGS[KERN_COUNT];

	static const Font::Info INFO;

public:
	CandaraFont() : KernedFont(INFO, GLYPHS, GLYPH_FIRST, GLYPH_FIRST + GLYPH_COUNT, 
		KERNINGS, KERN_FIRST, KERN_FIRST + KERN_COUNT, KERN_MAP_FIRST, KERN_MAP_FIRST + KERN_MAP_COUNT)
	{}
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}

#endif