// 
// POINTLESS TO MODIFY THIS FILE - IT'S AUTO-GENERATED BY COOK_FONT.PY from TEMPLATE_FONT.H
// 

#ifndef OCR_A_EXTENDED_FONT_INCLUDED
#define OCR_A_EXTENDED_FONT_INCLUDED

namespace engine {

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class OCR_A_ExtendedFont : public Font {
	static const uint GLYPH_FIRST = 32;
	static const uint GLYPH_COUNT = 224;

	static const Font::Glyph GLYPH_DATA[];
	static const Font::Glyph* const GLYPHS[GLYPH_COUNT];

	static const Font::Info INFO;

public:
	OCR_A_ExtendedFont() : Font(INFO, GLYPHS, GLYPH_FIRST, GLYPH_FIRST + GLYPH_COUNT)
	{}
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}

#endif
