// 
// POINTLESS TO MODIFY THIS FILE - IT'S AUTO-GENERATED BY COOK_FONT.PY from TEMPLATE_FONT.H
// 

#ifndef SLING_FONT_INCLUDED
#define SLING_FONT_INCLUDED

namespace engine {

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class SlingFont : public Font {
	static const uint GLYPH_FIRST = 32;
	static const uint GLYPH_COUNT = 184;

	static const uint KERN_FIRST = 34;
	static const uint KERN_COUNT = 88;

	static const uint KERN_MAP_FIRST = 34;
	static const uint KERN_MAP_COUNT = 89;

	static const Font::Glyph GLYPH_DATA[];
	static const Font::Glyph* const GLYPHS[GLYPH_COUNT];

	static const i8 KERN_DATA[][KERN_MAP_COUNT];
	static const i8* const KERNINGS[KERN_COUNT];

	static const Font::Info INFO;

public:
	SlingFont() : Font(INFO, 
					   GLYPHS, GLYPH_FIRST, GLYPH_FIRST + GLYPH_COUNT, 
					   KERNINGS, KERN_FIRST, KERN_FIRST + KERN_COUNT, KERN_MAP_FIRST, KERN_MAP_FIRST + KERN_MAP_COUNT)
	{}
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

}

#endif
